{"uid":"2e11e04103377886","name":"Изменение данных юзера","fullName":"tests.api_tests.user.test_users.TestUsers#test_update_user","historyId":"1bd2963f5b04d3764f2ae0b1802c8175","time":{"start":1759810595189,"stop":1759810595189,"duration":0},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for LoginUserSchema\nemail\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type\npassword\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type","statusTrace":"request = <SubRequest 'auto_authorize' for <Function test_update_user>>\nauthentications_client = <clients.user.user_client.UserClient object at 0x7f405a2c2d50>\n\n    @pytest.fixture(autouse=True, scope=\"function\")\n    def auto_authorize(request, authentications_client: UserClient):\n        load_dotenv()\n        # Если у теста стоит mark no_auto_auth, то фикстуру пропускаем\n        if request.node.get_closest_marker(\"no_auto_authorize\"):\n            return\n        \"\"\"\n        Авто-авторизация перед каждым тестом\n        Берём логин/пароль из data_user.json\n        Получаем токен и кладём в data_user.json\n        \"\"\"\n>       login_request = LoginUserSchema(\n            email=Constants.email,\n            password=Constants.password\n        )\nE       pydantic_core._pydantic_core.ValidationError: 2 validation errors for LoginUserSchema\nE       email\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.11/v/string_type\nE       password\nE         Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\nE           For further information visit https://errors.pydantic.dev/2.11/v/string_type\n\nfixtures/authenticated_fixtures.py:29: ValidationError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1759810595064,"stop":1759810595065,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1759810595065,"stop":1759810595094,"duration":29},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1759810595065,"stop":1759810595065,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1759810595094,"stop":1759810595094,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1759810595094,"stop":1759810595095,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authentications_client","time":{"start":1759810595189,"stop":1759810595212,"duration":23},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auto_authorize","time":{"start":1759810595212,"stop":1759810595212,"duration":0},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for LoginUserSchema\nemail\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type\npassword\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/PetProject/PetProject/fixtures/authenticated_fixtures.py\", line 29, in auto_authorize\n    login_request = LoginUserSchema(\n                    ^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"epic","value":"API tests"},{"name":"parentSuite","value":"API tests"},{"name":"feature","value":"Тесты на юзера"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsers"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"2441-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api_tests.user.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":1,"unknown":0,"total":4},"items":[{"uid":"60f3942c812ec8a1","reportUrl":"https://MikhailLuginin.github.io/PetProject/23//#testresult/60f3942c812ec8a1","status":"broken","statusDetails":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\ndata\n  Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing","time":{"start":1759810310565,"stop":1759810310634,"duration":69}},{"uid":"9dbe3a05ccdadbba","reportUrl":"https://MikhailLuginin.github.io/PetProject/20//#testresult/9dbe3a05ccdadbba","status":"broken","statusDetails":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UserSchema\ndata\n  Field required [type=missing, input_value={'success': False, 'statu...en 4 and 30 characters'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing","time":{"start":1759762501683,"stop":1759762501770,"duration":87}},{"uid":"33f4628e96c51406","reportUrl":"https://MikhailLuginin.github.io/PetProject/19//#testresult/33f4628e96c51406","status":"passed","time":{"start":1759761233864,"stop":1759761234038,"duration":174}}]},"tags":[]},"source":"2e11e04103377886.json","parameterValues":[]}